Attempt to wrap main loop in a try-except that will deep sleep for an hour
I don't know why, but I've been getting some network-related errors trying to leave this
running on my fridge. Ex:

> 333@adafruit_connection_manager.p
> File "adafruit_connection_manager.py", line 333, in get_socket
> gaierror: (-2. 'Name or service not known')
>
> Code done running.
>
> Press any key to enter the REPL. Use CTRL-D to reload

I think this will catch that error, and cause the display to deep sleep for an hour before
trying again. If it doesn't display the error, I'm probably happy too. Could add some
error logging (somewhere external? to the drive?) so that I could debug if there are long
stretches where the display never updates, but unless I need them I think this is fine.